name: Add New Roadmap Items

on:
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create new roadmap issues
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          const newIssues = [
            { title: "Create a comprehensive README.md file", labels: ["documentation"] },
            { title: "Add API specifications for each microservice", labels: ["documentation"] },
            { title: "Set up CI/CD pipeline using GitHub Actions", labels: ["devops"] },
            { title: "Create issue templates for bug reports and feature requests", labels: ["documentation"] },
            { title: "Add CONTRIBUTING.md guidelines", labels: ["documentation"] },
            { title: "Choose and add an appropriate LICENSE file", labels: ["documentation"] },
            { title: "Create CODE_OF_CONDUCT.md", labels: ["documentation"] },
            { title: "Implement core functionality for account-service", labels: ["enhancement"] },
            { title: "Implement core functionality for payment-service", labels: ["enhancement"] },
            { title: "Develop comprehensive test suites for each service", labels: ["testing"] },
            { title: "Add Dockerfiles for each service", labels: ["devops"] }
          ];

          for (const issue of newIssues) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue.title,
              labels: issue.labels
            });
          }
